# Meta data du workflow
name: Exercice 2 Artefact
# Événement Déclancher
on:
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      # Récupère tout le code 
      - uses: actions/checkout@v7
      # Prepare l'environnement
      - uses: actions/setup-node@v7
        with:
          node-version: 24.18.0
      # Installer les dépendances 
      - run: npm ci
      # Lancer le build
      - run: npm run build
      # Verifier que le /dist existe
      - run: |
          if [ -d "dist" ]; then
            echo "Le dossier dist/ existe"
          else
            echo "Le dossier dist/ n'existe pas"
            exit 1
          fi
      # lancer les tests
      #- run: npm test
      # Sauvegarder dist/ comme artefact
      # ---- on sauvegarde le build dans un artefact pour le réutiliser dans d'autres jobs ou workflows
      - uses: actions/upload-artifact@v7
        with:
          name: build
          path: dist/
      # Ecrire un résumé du build
      - run: |
          echo "- Branche : ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Commit : ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- Lancé par : ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- Node : $(node -v)" >> $GITHUB_STEP_SUMMARY
          echo "- Taille de dist/ : $(du -sh dist | cut -f1)" >> $GITHUB_STEP_SUMMARY
