# Meta data du workflow
name: Hello World
# Événement Déclancher
on:
  push:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      # Récupère tout le code 
      - uses: actions/checkout@v7
      # Installe node.js
      - uses: actions/setup-node@v7
        with:
          node-version: 24.18.0
      - uses: actions/cache@v5
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
      # installer les dépendances
      - run: npm install
      # lancer les tests
      #- run: npm run test
      - run: |
          echo "Status ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "Ref du commit ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY

